service:
  golangci-lint-version: 1.51.x
run:
  deadline: 900s
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    - asasalint
    - containedctx
    - contextcheck
    - cyclop
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - err113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - importas
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varnamelen
    - wrapcheck
    - wsl
    - depguard # allow importing of package viamrtsp
    - gocritic # false positives in cgo calls
    - errcheck # gosec checks unhandled errors already
linters-settings:
  gci:
    sections:
      - standard
      - default
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
      - composites
  lll:
    line-length: 140
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - dupword
        - exhaustive
        - goconst
        - gosec
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
