// @generated by protoc-gen-es v1.10.0
// @generated from file src/proto/videostore.proto (package viammodules.service.videostore.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message viammodules.service.videostore.v1.FetchStreamRequest
 */
export const FetchStreamRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viammodules.service.videostore.v1.FetchStreamRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viammodules.service.videostore.v1.FetchStreamResponse
 */
export const FetchStreamResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viammodules.service.videostore.v1.FetchStreamResponse",
  () => [
    { no: 1, name: "video_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message viammodules.service.videostore.v1.FetchRequest
 */
export const FetchRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viammodules.service.videostore.v1.FetchRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viammodules.service.videostore.v1.FetchResponse
 */
export const FetchResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viammodules.service.videostore.v1.FetchResponse",
  () => [
    { no: 1, name: "video_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message viammodules.service.videostore.v1.SaveRequest
 */
export const SaveRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viammodules.service.videostore.v1.SaveRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "from", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viammodules.service.videostore.v1.SaveResponse
 */
export const SaveResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viammodules.service.videostore.v1.SaveResponse",
  () => [
    { no: 1, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

