// @generated by protoc-gen-es v1.10.0
// @generated from file src/proto/videostore.proto (package viammodules.service.videostore.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message viammodules.service.videostore.v1.FetchStreamRequest
 */
export declare class FetchStreamRequest extends Message<FetchStreamRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * @generated from field: string to = 3;
   */
  to: string;

  /**
   * e.g., "mp4", "fmp4"
   *
   * @generated from field: string container = 4;
   */
  container: string;

  constructor(data?: PartialMessage<FetchStreamRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.FetchStreamRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchStreamRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchStreamRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchStreamRequest;

  static equals(a: FetchStreamRequest | PlainMessage<FetchStreamRequest> | undefined, b: FetchStreamRequest | PlainMessage<FetchStreamRequest> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.FetchStreamResponse
 */
export declare class FetchStreamResponse extends Message<FetchStreamResponse> {
  /**
   * @generated from field: bytes video_data = 1;
   */
  videoData: Uint8Array;

  constructor(data?: PartialMessage<FetchStreamResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.FetchStreamResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchStreamResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchStreamResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchStreamResponse;

  static equals(a: FetchStreamResponse | PlainMessage<FetchStreamResponse> | undefined, b: FetchStreamResponse | PlainMessage<FetchStreamResponse> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.FetchRequest
 */
export declare class FetchRequest extends Message<FetchRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * @generated from field: string to = 3;
   */
  to: string;

  /**
   * @generated from field: string container = 4;
   */
  container: string;

  constructor(data?: PartialMessage<FetchRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.FetchRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchRequest;

  static equals(a: FetchRequest | PlainMessage<FetchRequest> | undefined, b: FetchRequest | PlainMessage<FetchRequest> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.FetchResponse
 */
export declare class FetchResponse extends Message<FetchResponse> {
  /**
   * @generated from field: bytes video_data = 1;
   */
  videoData: Uint8Array;

  constructor(data?: PartialMessage<FetchResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.FetchResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchResponse;

  static equals(a: FetchResponse | PlainMessage<FetchResponse> | undefined, b: FetchResponse | PlainMessage<FetchResponse> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.SaveRequest
 */
export declare class SaveRequest extends Message<SaveRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * @generated from field: string to = 3;
   */
  to: string;

  /**
   * @generated from field: string container = 4;
   */
  container: string;

  constructor(data?: PartialMessage<SaveRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.SaveRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveRequest;

  static equals(a: SaveRequest | PlainMessage<SaveRequest> | undefined, b: SaveRequest | PlainMessage<SaveRequest> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.SaveResponse
 */
export declare class SaveResponse extends Message<SaveResponse> {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  constructor(data?: PartialMessage<SaveResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.SaveResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SaveResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SaveResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SaveResponse;

  static equals(a: SaveResponse | PlainMessage<SaveResponse> | undefined, b: SaveResponse | PlainMessage<SaveResponse> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.GetStorageStateRequest
 */
export declare class GetStorageStateRequest extends Message<GetStorageStateRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<GetStorageStateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.GetStorageStateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStorageStateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStorageStateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStorageStateRequest;

  static equals(a: GetStorageStateRequest | PlainMessage<GetStorageStateRequest> | undefined, b: GetStorageStateRequest | PlainMessage<GetStorageStateRequest> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.GetStorageStateResponse
 */
export declare class GetStorageStateResponse extends Message<GetStorageStateResponse> {
  /**
   * @generated from field: viammodules.service.videostore.v1.StorageState state = 1;
   */
  state?: StorageState;

  constructor(data?: PartialMessage<GetStorageStateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.GetStorageStateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStorageStateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStorageStateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStorageStateResponse;

  static equals(a: GetStorageStateResponse | PlainMessage<GetStorageStateResponse> | undefined, b: GetStorageStateResponse | PlainMessage<GetStorageStateResponse> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.StorageState
 */
export declare class StorageState extends Message<StorageState> {
  /**
   * @generated from field: int64 storage_used_bytes = 1;
   */
  storageUsedBytes: bigint;

  /**
   * @generated from field: int64 total_duration_ms = 2;
   */
  totalDurationMs: bigint;

  /**
   * @generated from field: int32 video_count = 3;
   */
  videoCount: number;

  /**
   * @generated from field: repeated viammodules.service.videostore.v1.VideoRange ranges = 4;
   */
  ranges: VideoRange[];

  /**
   * @generated from field: int32 storage_limit_gb = 5;
   */
  storageLimitGb: number;

  /**
   * @generated from field: double device_storage_remaining_gb = 6;
   */
  deviceStorageRemainingGb: number;

  /**
   * @generated from field: string storage_path = 7;
   */
  storagePath: string;

  constructor(data?: PartialMessage<StorageState>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.StorageState";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StorageState;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StorageState;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StorageState;

  static equals(a: StorageState | PlainMessage<StorageState> | undefined, b: StorageState | PlainMessage<StorageState> | undefined): boolean;
}

/**
 * @generated from message viammodules.service.videostore.v1.VideoRange
 */
export declare class VideoRange extends Message<VideoRange> {
  /**
   * @generated from field: string from = 1;
   */
  from: string;

  /**
   * @generated from field: string to = 2;
   */
  to: string;

  constructor(data?: PartialMessage<VideoRange>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viammodules.service.videostore.v1.VideoRange";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoRange;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoRange;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoRange;

  static equals(a: VideoRange | PlainMessage<VideoRange> | undefined, b: VideoRange | PlainMessage<VideoRange> | undefined): boolean;
}

