// @generated by protoc-gen-connect-es v1.6.1
// @generated from file src/proto/videostore.proto (package viammodules.service.videostore.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FetchRequest, FetchResponse, FetchStreamRequest, FetchStreamResponse, GetStorageStateRequest, GetStorageStateResponse, SaveRequest, SaveResponse } from "./videostore_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service viammodules.service.videostore.v1.videostoreService
 */
export const videostoreService = {
  typeName: "viammodules.service.videostore.v1.videostoreService",
  methods: {
    /**
     * @generated from rpc viammodules.service.videostore.v1.videostoreService.FetchStream
     */
    fetchStream: {
      name: "FetchStream",
      I: FetchStreamRequest,
      O: FetchStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc viammodules.service.videostore.v1.videostoreService.Fetch
     */
    fetch: {
      name: "Fetch",
      I: FetchRequest,
      O: FetchResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viammodules.service.videostore.v1.videostoreService.Save
     */
    save: {
      name: "Save",
      I: SaveRequest,
      O: SaveResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viammodules.service.videostore.v1.videostoreService.GetStorageState
     */
    getStorageState: {
      name: "GetStorageState",
      I: GetStorageStateRequest,
      O: GetStorageStateResponse,
      kind: MethodKind.Unary,
    },
  }
};

