// @generated by protoc-gen-connect-es v1.6.1
// @generated from file src/proto/videostore.proto (package viammodules.service.videostore.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FetchRequest, FetchResponse, FetchStreamRequest, FetchStreamResponse, SaveRequest, SaveResponse } from "./videostore_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service viammodules.service.videostore.v1.videostoreService
 */
export declare const videostoreService: {
  readonly typeName: "viammodules.service.videostore.v1.videostoreService",
  readonly methods: {
    /**
     * @generated from rpc viammodules.service.videostore.v1.videostoreService.FetchStream
     */
    readonly fetchStream: {
      readonly name: "FetchStream",
      readonly I: typeof FetchStreamRequest,
      readonly O: typeof FetchStreamResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * Unary fetch between [from, to]
     *
     * @generated from rpc viammodules.service.videostore.v1.videostoreService.Fetch
     */
    readonly fetch: {
      readonly name: "Fetch",
      readonly I: typeof FetchRequest,
      readonly O: typeof FetchResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Unary save between [from, to]
     *
     * @generated from rpc viammodules.service.videostore.v1.videostoreService.Save
     */
    readonly save: {
      readonly name: "Save",
      readonly I: typeof SaveRequest,
      readonly O: typeof SaveResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

