// @generated by protoc-gen-es v2.8.0
// @generated from file src/proto/videostore.proto (package viammodules.service.videostore.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file src/proto/videostore.proto.
 */
export declare const file_src_proto_videostore: GenFile;

/**
 * @generated from message viammodules.service.videostore.v1.FetchStreamRequest
 */
export declare type FetchStreamRequest = Message<"viammodules.service.videostore.v1.FetchStreamRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Date-time in format YYYY-MM-DD_HH-MM-SS
   *
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * Date-time in format YYYY-MM-DD_HH-MM-SS
   *
   * @generated from field: string to = 3;
   */
  to: string;
};

/**
 * Describes the message viammodules.service.videostore.v1.FetchStreamRequest.
 * Use `create(FetchStreamRequestSchema)` to create a new message.
 */
export declare const FetchStreamRequestSchema: GenMessage<FetchStreamRequest>;

/**
 * @generated from message viammodules.service.videostore.v1.FetchStreamResponse
 */
export declare type FetchStreamResponse = Message<"viammodules.service.videostore.v1.FetchStreamResponse"> & {
  /**
   * @generated from field: bytes video_data = 1;
   */
  videoData: Uint8Array;
};

/**
 * Describes the message viammodules.service.videostore.v1.FetchStreamResponse.
 * Use `create(FetchStreamResponseSchema)` to create a new message.
 */
export declare const FetchStreamResponseSchema: GenMessage<FetchStreamResponse>;

/**
 * @generated from message viammodules.service.videostore.v1.FetchRequest
 */
export declare type FetchRequest = Message<"viammodules.service.videostore.v1.FetchRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Date-time in format YYYY-MM-DD_HH-MM-SS
   *
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * Date-time in format YYYY-MM-DD_HH-MM-SS
   *
   * @generated from field: string to = 3;
   */
  to: string;
};

/**
 * Describes the message viammodules.service.videostore.v1.FetchRequest.
 * Use `create(FetchRequestSchema)` to create a new message.
 */
export declare const FetchRequestSchema: GenMessage<FetchRequest>;

/**
 * @generated from message viammodules.service.videostore.v1.FetchResponse
 */
export declare type FetchResponse = Message<"viammodules.service.videostore.v1.FetchResponse"> & {
  /**
   * Raw video bytes for the requested interval
   *
   * @generated from field: bytes video_data = 1;
   */
  videoData: Uint8Array;
};

/**
 * Describes the message viammodules.service.videostore.v1.FetchResponse.
 * Use `create(FetchResponseSchema)` to create a new message.
 */
export declare const FetchResponseSchema: GenMessage<FetchResponse>;

/**
 * @generated from message viammodules.service.videostore.v1.SaveRequest
 */
export declare type SaveRequest = Message<"viammodules.service.videostore.v1.SaveRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Date-time in format YYYY-MM-DD_HH-MM-SS
   *
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * Date-time in format YYYY-MM-DD_HH-MM-SS
   *
   * @generated from field: string to = 3;
   */
  to: string;
};

/**
 * Describes the message viammodules.service.videostore.v1.SaveRequest.
 * Use `create(SaveRequestSchema)` to create a new message.
 */
export declare const SaveRequestSchema: GenMessage<SaveRequest>;

/**
 * @generated from message viammodules.service.videostore.v1.SaveResponse
 */
export declare type SaveResponse = Message<"viammodules.service.videostore.v1.SaveResponse"> & {
  /**
   * Filename (or identifier) of the saved artifact
   *
   * @generated from field: string filename = 1;
   */
  filename: string;
};

/**
 * Describes the message viammodules.service.videostore.v1.SaveResponse.
 * Use `create(SaveResponseSchema)` to create a new message.
 */
export declare const SaveResponseSchema: GenMessage<SaveResponse>;

/**
 * @generated from service viammodules.service.videostore.v1.videostoreService
 */
export declare const videostoreService: GenService<{
  /**
   * @generated from rpc viammodules.service.videostore.v1.videostoreService.FetchStream
   */
  fetchStream: {
    methodKind: "server_streaming";
    input: typeof FetchStreamRequestSchema;
    output: typeof FetchStreamResponseSchema;
  },
  /**
   * Unary fetch between [from, to]
   *
   * @generated from rpc viammodules.service.videostore.v1.videostoreService.Fetch
   */
  fetch: {
    methodKind: "unary";
    input: typeof FetchRequestSchema;
    output: typeof FetchResponseSchema;
  },
  /**
   * Unary save between [from, to]
   *
   * @generated from rpc viammodules.service.videostore.v1.videostoreService.Save
   */
  save: {
    methodKind: "unary";
    input: typeof SaveRequestSchema;
    output: typeof SaveResponseSchema;
  },
}>;

