// @generated by protoc-gen-es v2.8.0
// @generated from file src/proto/videostore.proto (package viammodules.service.videostore.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file src/proto/videostore.proto.
 */
export const file_src_proto_videostore = /*@__PURE__*/
  fileDesc("ChpzcmMvcHJvdG8vdmlkZW9zdG9yZS5wcm90bxIhdmlhbW1vZHVsZXMuc2VydmljZS52aWRlb3N0b3JlLnYxIjwKEkZldGNoU3RyZWFtUmVxdWVzdBIMCgRuYW1lGAEgASgJEgwKBGZyb20YAiABKAkSCgoCdG8YAyABKAkiKQoTRmV0Y2hTdHJlYW1SZXNwb25zZRISCgp2aWRlb19kYXRhGAEgASgMIjYKDEZldGNoUmVxdWVzdBIMCgRuYW1lGAEgASgJEgwKBGZyb20YAiABKAkSCgoCdG8YAyABKAkiIwoNRmV0Y2hSZXNwb25zZRISCgp2aWRlb19kYXRhGAEgASgMIjUKC1NhdmVSZXF1ZXN0EgwKBG5hbWUYASABKAkSDAoEZnJvbRgCIAEoCRIKCgJ0bxgDIAEoCSIgCgxTYXZlUmVzcG9uc2USEAoIZmlsZW5hbWUYASABKAky6AIKEXZpZGVvc3RvcmVTZXJ2aWNlEn4KC0ZldGNoU3RyZWFtEjUudmlhbW1vZHVsZXMuc2VydmljZS52aWRlb3N0b3JlLnYxLkZldGNoU3RyZWFtUmVxdWVzdBo2LnZpYW1tb2R1bGVzLnNlcnZpY2UudmlkZW9zdG9yZS52MS5GZXRjaFN0cmVhbVJlc3BvbnNlMAESagoFRmV0Y2gSLy52aWFtbW9kdWxlcy5zZXJ2aWNlLnZpZGVvc3RvcmUudjEuRmV0Y2hSZXF1ZXN0GjAudmlhbW1vZHVsZXMuc2VydmljZS52aWRlb3N0b3JlLnYxLkZldGNoUmVzcG9uc2USZwoEU2F2ZRIuLnZpYW1tb2R1bGVzLnNlcnZpY2UudmlkZW9zdG9yZS52MS5TYXZlUmVxdWVzdBovLnZpYW1tb2R1bGVzLnNlcnZpY2UudmlkZW9zdG9yZS52MS5TYXZlUmVzcG9uc2VCEloQLi92aWRlb3N0b3JlLWFwaWIGcHJvdG8z");

/**
 * Describes the message viammodules.service.videostore.v1.FetchStreamRequest.
 * Use `create(FetchStreamRequestSchema)` to create a new message.
 */
export const FetchStreamRequestSchema = /*@__PURE__*/
  messageDesc(file_src_proto_videostore, 0);

/**
 * Describes the message viammodules.service.videostore.v1.FetchStreamResponse.
 * Use `create(FetchStreamResponseSchema)` to create a new message.
 */
export const FetchStreamResponseSchema = /*@__PURE__*/
  messageDesc(file_src_proto_videostore, 1);

/**
 * Describes the message viammodules.service.videostore.v1.FetchRequest.
 * Use `create(FetchRequestSchema)` to create a new message.
 */
export const FetchRequestSchema = /*@__PURE__*/
  messageDesc(file_src_proto_videostore, 2);

/**
 * Describes the message viammodules.service.videostore.v1.FetchResponse.
 * Use `create(FetchResponseSchema)` to create a new message.
 */
export const FetchResponseSchema = /*@__PURE__*/
  messageDesc(file_src_proto_videostore, 3);

/**
 * Describes the message viammodules.service.videostore.v1.SaveRequest.
 * Use `create(SaveRequestSchema)` to create a new message.
 */
export const SaveRequestSchema = /*@__PURE__*/
  messageDesc(file_src_proto_videostore, 4);

/**
 * Describes the message viammodules.service.videostore.v1.SaveResponse.
 * Use `create(SaveResponseSchema)` to create a new message.
 */
export const SaveResponseSchema = /*@__PURE__*/
  messageDesc(file_src_proto_videostore, 5);

/**
 * @generated from service viammodules.service.videostore.v1.videostoreService
 */
export const videostoreService = /*@__PURE__*/
  serviceDesc(file_src_proto_videostore, 0);

