name: 'Build Module'
description: 'Builds the viamrtsp module using Docker'
inputs:
  target_os:
    description: 'Target OS'
    required: true
  target_arch:
    description: 'Target architecture'
    required: true
  docker_image:
    description: 'Docker image to use for building'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23 # match go.mod

    - name: Pull Docker image
      run: docker pull ${{ inputs.docker_image }}
      shell: bash

    - name: Build and package using Docker
      run: |
        docker run --rm \
          -e TARGET_OS=${{ inputs.target_os }} \
          -e TARGET_ARCH=${{ inputs.target_arch }} \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          ${{ inputs.docker_image }} \
          sh -c "make module"
      shell: bash

    - name: Verify module.tar.gz exists recursively
      run: |
        if find . -name module.tar.gz | grep -q .; then
          echo "module.tar.gz exists"
        else
          echo "module.tar.gz does not exist"
          exit 1
        fi
      shell: bash
