name: 'Build Module'
description: 'Builds the viamrtsp module using Docker or natively'
inputs:
  target_os:
    description: 'Target OS'
    required: true
  target_arch:
    description: 'Target architecture'
    required: true
  docker_image:
    description: 'Docker image to use for building (optional - if not provided, builds natively)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build using Docker
      if: inputs.docker_image != ''
      run: |
        docker pull ${{ inputs.docker_image }}
        docker run --rm \
          -e TARGET_OS=${{ inputs.target_os }} \
          -e TARGET_ARCH=${{ inputs.target_arch }} \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          ${{ inputs.docker_image }} \
          sh -c "make module"
      shell: bash

    - name: Build natively
      if: inputs.docker_image == ''
      run: make module
      shell: bash

    - name: Verify module.tar.gz exists
      run: |
        if find . -name module.tar.gz | grep -q .; then
          echo "module.tar.gz exists"
        else
          echo "module.tar.gz does not exist"
          exit 1
        fi
      shell: bash
