name: Helper workflow to build viamrtsp in a deploy-to-production Docker container

on:
  workflow_call:
    inputs:
      target_os:
        required: true
        type: string
      target_arch:
        required: true
        type: string
      docker_image:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.13

    - name: Pull Docker image
      run: docker pull ${{ inputs.docker_image }}

    - name: Build and package inside container
      run: |
        docker run --rm \
          -e TARGET_OS=${{ inputs.target_os }} \
          -e TARGET_ARCH=${{ inputs.target_arch }} \
          -v "$(pwd):/workspace" \
          -w /workspace \
          ${{ inputs.docker_image }} \
          sh -c "make module"

    - name: Verify module.tar.gz exists
      run: |
        if find . -name module.tar.gz | grep -q .; then
          echo "module.tar.gz exists"
        else
          echo "module.tar.gz does not exist"
          exit 1
        fi
